<a href="https://colab.research.google.com/github/KrisSandy/TheMaskOfPython/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

NumPy's main object is homogeneous multidimensional array. 

In [0]:
import numpy as np

### Creating Arrays

* Arrays can be created from a list or tuple

In [0]:
a = np.array([2,3,4])
b = np.array([(1.5,2,3),(4,5,6)])
print(a)
print(b)

[2 3 4]
[[1.5 2.  3. ]
 [4.  5.  6. ]]


* Type of the array can be specified at creation time

In [0]:
c = np.array([[1,2], [3,4]], dtype='complex')
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

* **np.zeros**: creates an array full of zeros
* **np.ones**: creates an array full of ones
* **np.empty**: creates an array with random values

*By default, the dtype of the created array is `float64`*

In [0]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [0]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [0]:
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

* **np.arange**: to create an array with sequence numbers (analogous to range)

In [0]:
print(np.arange(15))
print(np.arange(10,20,2))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[10 12 14 16 18]


* **np.linspace**: generates number of elements we want between the specified range and with equal spacing between numbers

In [0]:
np.linspace(0,2,8)

array([0.        , 0.28571429, 0.57142857, 0.85714286, 1.14285714,
       1.42857143, 1.71428571, 2.        ])

### Array Properties


Dimentions of a NumPy array are called axes. 

* **ndarray.ndim**: number of axes of the array
* **ndarray.shape**: dimensions of the array
* **ndarray.size**: number of elements in the array, equal to product of the elements of `shape`
* **ndarray.dtype**: type of the elements in the array
* **ndarray.itemsize**: size of each element of the array

In [0]:
a = np.arange(15)
print("Dimentions of array : {}".format(a.ndim))
a = a.reshape(3,5)
print("Dimentions of array after reshape: {}".format(a.ndim))
print("Shape of array: {}".format(a.shape))
print("Size of array: {}".format(a.size))
print("Item size of array: {}".format(a.itemsize))
print("dtype of array: {}".format(a.dtype))
print("type of array: {}".format(type(a)))


Dimentions of array : 1
Dimentions of array after reshape: 2
Shape of array: (3, 5)
Size of array: 15
Item size of array: 8
dtype of array: int64
type of array: <class 'numpy.ndarray'>


### Basic Operations

Arthematic operators (+, -, **, * etc) are applied elementwise, and this will create a new array.

In [0]:
a = np.array([10,20,30,40,50])
a < 35

array([ True,  True,  True, False, False])

* Matrix multiplication can be done using `@` operator or `np.dot`
* type casting is only done in updward direction i.e. int to float, but downcasting is not done automatically. This behaviour is called upcasting

### Universal Functions

NumPy provides several mathematical functions such as sin, cos, exp, log. These functions produce an array as result.



In [0]:
b = np.arange(12).reshape(3,4)
b.sum()

66

`axis` parameter can be used to apply an operation along the specific axis of an array

In [0]:
b.sum(axis=0) # 0 -> column wise, 1 -> row wise

array([12, 15, 18, 21])

In [0]:
print(b.cumsum())
print(b.cumsum(axis=0))

[ 0  1  3  6 10 15 21 28 36 45 55 66]
[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]


#### Examples 


Function | Usage
--- | ---
all | Test if all elements evaluate to True i.e. if zero is present or not
any | Test if any elements evaluate to True i.e. if its all zeros
apply_along_axis | Apply a function along the given axis
apply_over_axis | Apply a function over multiple axis
argmax | Returns the indices of the max value along an axis
argmin | Returns the indices of the min value along an axis
amax | Returns the max value of array
meshgrid | Make a coordinate Matrix from coordinate Vector
c_ | concatinates the arrays column wise
ravel | flatten array


In [0]:
print(np.all([-1, 4, 5]))
print(np.all([-1, 4, 0]))
print(np.any([[True, False], [False, False]]))

True
False
True


Meshgrid produces coordinate matrix meaning, for every point in x and y, it produces (x, y)

In [0]:
x, y = np.meshgrid(np.array([1,2]), np.array([4,5]))
print(x.ravel())
print(y.ravel())
z = np.c_[x.ravel(), y.ravel()]
print(z)

[1 2 1 2]
[4 4 5 5]
[[1 4]
 [2 4]
 [1 5]
 [2 5]]


### Indexing, Slicing and Iterating

In [0]:
a = np.arange(10) ** 2
print(a)
print(a[2:4])
print(a[ : : -1]) # reversed array
a[:6:2] = -100
print(a)
for i in a:
    print(i**(1/2))

[ 0  1  4  9 16 25 36 49 64 81]
[4 9]
[81 64 49 36 25 16  9  4  1  0]
[-100    1 -100    9 -100   25   36   49   64   81]
nan
1.0
nan
3.0
nan
5.0
6.0
7.0
8.0
9.0


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in power
  
